### ISSUE TITLE
Item Entities no longer spawn

### ISSUE THREAD

**Issue by DoodlesQ** [Funwayguy/RealisticItemDrops#36]
I've encountered an odd issue, that seems to be caused by this mod. When running this mod on my server, at some point the following errors are logged to the server:

```
31.03 20:42:31 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_211]
31.03 20:42:31 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_211]
31.03 20:42:31 [Server] INFO at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
31.03 20:42:31 [Server] INFO ... 5 more
31.03 20:42:31 [Server] Server thread/WARN Skipping Entity with id realdrops:item_loot
31.03 20:42:31 [Server] Server thread/WARN Skipping Entity with id realdrops:item_loot
31.03 20:44:05 [Server] Server thread/WARN BunniSloooth moved wrongly!
31.03 20:44:23 [Server] Server thread/WARN Skipping Entity with id realdrops:item_loot
31.03 20:44:23 [Server] Server thread/WARN Skipping Entity with id realdrops:item_loot
31.03 20:44:23 [Server] Server thread/WARN Skipping Entity with id realdrops:item_loot
31.03 20:44:23 [Server] Server thread/WARN Skipping Entity with id realdrops:item_loot
31.03 20:46:11 [Server] Server thread/WARN Skipping Entity with id realdrops:item_loot
31.03 20:46:11 [Server] Server thread/WARN Skipping Entity with id realdrops:item_loot
31.03 20:46:11 [Server] Server thread/WARN Skipping Entity with id realdrops:item_loot
31.03 20:46:15 [Server] Server thread/INFO [STDOUT]: [com.yyon.grapplinghook.controllers.SegmentHandler:updatesegment:278]: Warning: number recursions exceeded
```

These errors are accompanied by the removal of all item entities on the server. Blocks no longer drop items and items dropped by players are deleted.  I have yet to find a way to solve this: the world simply no longer spawns item entities.
This has occurred twice now, and the lack of item drops persists even when the mod has been deleted from the server and client.

There is one other mod outputting an error in that chain (Grappling Hook mod by yyonne), but removing that mod also has no affect on the presence of item drops, and that mod does not alter the item entity in a way that could cause this, to my knowledge. I have also contacted yyonne about this issue, just in case.

**Comment by DoodlesQ** [comment]
The problem has been solved by another moderator on the server. Somehow the gamerule doTileDrops was set to false on our server, despite none of the operators issuing that command and there being no log of it in the server. We can't figure out how it happened, but at least we fixed it.
