### ISSUE TITLE
NPE in onPlayerClickBlock

### ISSUE THREAD

**Issue by codewarrior0** [Funwayguy/RealisticItemDrops#4]
Error occurs occasionally when right-clicking on any block.

```
java.lang.NullPointerException: Unexpected error
	at realdrops.handlers.EventHandler.onPlayerClickBlock(EventHandler.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_345_EventHandler_onPlayerClickBlock_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:981)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:386)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1517)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2176)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1960)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1748)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369)
	at net.minecraft.client.main.Main.main(SourceFile:124)
```

Minecraft 1.9.4
RealisticItemDrops-1.0.3.jar
forge-1.9.4-12.17.0.1957-universal.jar

Auto Pickup is set to True.

**Comment by Funwayguy** [comment]
Thanks for the report. Pushing out a bug fix now to resolve this, should be downloadable shortly.
